/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GroupsGroupIdRouteImport } from './routes/groups.$groupId'
import { Route as GroupsGroupIdIndexRouteImport } from './routes/groups.$groupId.index'
import { Route as GroupsGroupIdHistoryRouteImport } from './routes/groups.$groupId.history'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdRoute = GroupsGroupIdRouteImport.update({
  id: '/groups/$groupId',
  path: '/groups/$groupId',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdIndexRoute = GroupsGroupIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GroupsGroupIdRoute,
} as any)
const GroupsGroupIdHistoryRoute = GroupsGroupIdHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => GroupsGroupIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/groups/$groupId': typeof GroupsGroupIdRouteWithChildren
  '/groups/$groupId/history': typeof GroupsGroupIdHistoryRoute
  '/groups/$groupId/': typeof GroupsGroupIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/groups/$groupId/history': typeof GroupsGroupIdHistoryRoute
  '/groups/$groupId': typeof GroupsGroupIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/groups/$groupId': typeof GroupsGroupIdRouteWithChildren
  '/groups/$groupId/history': typeof GroupsGroupIdHistoryRoute
  '/groups/$groupId/': typeof GroupsGroupIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/groups/$groupId'
    | '/groups/$groupId/history'
    | '/groups/$groupId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/groups/$groupId/history' | '/groups/$groupId'
  id:
    | '__root__'
    | '/'
    | '/groups/$groupId'
    | '/groups/$groupId/history'
    | '/groups/$groupId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GroupsGroupIdRoute: typeof GroupsGroupIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId': {
      id: '/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof GroupsGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId/': {
      id: '/groups/$groupId/'
      path: '/'
      fullPath: '/groups/$groupId/'
      preLoaderRoute: typeof GroupsGroupIdIndexRouteImport
      parentRoute: typeof GroupsGroupIdRoute
    }
    '/groups/$groupId/history': {
      id: '/groups/$groupId/history'
      path: '/history'
      fullPath: '/groups/$groupId/history'
      preLoaderRoute: typeof GroupsGroupIdHistoryRouteImport
      parentRoute: typeof GroupsGroupIdRoute
    }
  }
}

interface GroupsGroupIdRouteChildren {
  GroupsGroupIdHistoryRoute: typeof GroupsGroupIdHistoryRoute
  GroupsGroupIdIndexRoute: typeof GroupsGroupIdIndexRoute
}

const GroupsGroupIdRouteChildren: GroupsGroupIdRouteChildren = {
  GroupsGroupIdHistoryRoute: GroupsGroupIdHistoryRoute,
  GroupsGroupIdIndexRoute: GroupsGroupIdIndexRoute,
}

const GroupsGroupIdRouteWithChildren = GroupsGroupIdRoute._addFileChildren(
  GroupsGroupIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GroupsGroupIdRoute: GroupsGroupIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
